// <auto-generated />
using System;
using ClinicaDocMais.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaDocMais.Migrations
{
    [DbContext(typeof(ClinicaContext))]
    [Migration("20260427191850_agendamento")]
    partial class agendamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClinicaDocMais.Models.AgendamentoModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MediconumerodocrmMedico")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cpfPaciente")
                        .HasColumnType("longtext");

                    b.Property<string>("crmMedico")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("dataHoradeAgendamentoMedico")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("medicoPresente")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("pacientePresente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("pacientecpf")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("MediconumerodocrmMedico");

                    b.HasIndex("pacientecpf");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("ClinicaDocMais.Models.ChamaModel", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("consultorio")
                        .HasColumnType("longtext");

                    b.Property<string>("nomePaciente")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Chamadas");
                });

            modelBuilder.Entity("ClinicaDocMais.Models.MedicoModel", b =>
                {
                    b.Property<string>("numerodocrmMedico")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("dataNascimentoMedico")
                        .HasColumnType("longtext");

                    b.Property<string>("emailMedico")
                        .HasColumnType("longtext");

                    b.Property<string>("especialidade")
                        .HasColumnType("longtext");

                    b.Property<string>("nomedoMedico")
                        .HasColumnType("longtext");

                    b.Property<string>("telefoneMedico")
                        .HasColumnType("longtext");

                    b.HasKey("numerodocrmMedico");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("ClinicaDocMais.Models.PacienteModel", b =>
                {
                    b.Property<string>("cpf")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("dataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("cpf");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaDocMais.Models.AgendamentoModel", b =>
                {
                    b.HasOne("ClinicaDocMais.Models.MedicoModel", "Medico")
                        .WithMany()
                        .HasForeignKey("MediconumerodocrmMedico");

                    b.HasOne("ClinicaDocMais.Models.PacienteModel", "paciente")
                        .WithMany()
                        .HasForeignKey("pacientecpf");

                    b.Navigation("Medico");

                    b.Navigation("paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
